language: node_js
services: mongodb
addons:
  code_climate:
    repo_token: e26a7ad48606ff4d7140e326418fee29ce708a1feeb741d5c4183b8dde81bb47
notifications:
  email: false
  slack:
    secure: cGIjn10k+X70YpX89TSPQYYIUKzz/xseJ7nzUjH7VE478QGQKOzl31ZN+8EFSxWtaYxNH38/so5hgv3ulkYPWt/J3UcbhjxXN7a+xiASwku6/KtxnPT28EogDdkvN3smsLXJmjsUfKoJUH7bIVeFYESc7Qjznk9Fdv9iBmTC6xcxWFbaY7v6PqqPOTkkwchWYIFykxiiLlHeymw8vJTqpJIHuyhhpkKLpRiZw3X0EyDzagPLNQAJdeUogbxEaRxHt1geSIZAE5iVar+N+2utlA4Dj1UE8RodOBypLkDXHKl/DM61deBIy+6ZVbpMopbBdPE3QYxWV1Cp39aqJ0BFXPqm+iacLRqiJZKplHPGW1Y96AvcH9J9CmkY/6EYyoO9GgznMo1SZnvIDqEabo/L91qePiPsZYZAtF/Sj6JDRoJAqv59j3M+joQBKvjF8QebqosgnMXMGw5Kgi+H7x0aLxWND8cnBp8/lltET5Yqpm86+/j7NxieVPW20AXLOwzxi5K25CX2j3wuMjOwofVPJoKM7+Tulk+zTiaTKJuGZHXLdPoTLRHfPPc2n9peEo9BGX4+lkmCCyOnTofB537worDf+pNc+RpcZhTaMKsG+wOPw6Q4fBsk8NWxi6PcY5KRzB/Bc9E1QU2beZcPTxbaNqsi3ptdJmK/XXD650ixUGQ=
node_js: 6
cache:
  directories:
  - node_modules
script:
- yarn lint
- yarn coverage
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: aleksander.ginovski@gmail.com
  api_key:
    secure: Ajs0xNGdHAHsMBXAufNjlXaWXQ/U+EXPNPv2N8lGkpK360IKyddENrCBuAtYOYMK/epyopbB21LHStajUKxY/LApZFEEiMxg4/8egEdH+1l+za6eViQDS5a5xpi2n2E9b7wfNNQe43ySldWizX1Lu6zQ50bGW9gSyxGS2qiyqYCorWZgupUFkXfGOqiZqKJjVYAAIZS5+iwEsXXRfJQIsAzjFJRkB8E+TZ/AhhKBO2wbQCAD7MxpS7RKyllnp/MXYz9gl5QuM4qG83cmNZxxTeVqwSwgjlkzMzKWcPLMriz0TOuvBpMXzNOtI5zcAc0EPDl/huaS4W7fuel3uU5X5zbVHLg/udvGYPAaUHo3zrwnJCIUZIBxgY9P2ScZW4lhbKdd4feYv+No37BSJLsRbPYv8Yc1JfEekyCp3QPEpQE/++Lsbk27G77HM+3XOMrQRjrhrR784XsL+PlYt8VajE0bQ4r0T/6GpTG9KIH1I1id2WjyQdAkuSu0LCmGIq8RRxJTehTwoBo8Vo2TYEu7JRaAZ9hHTcopVu1WB3dBbz7xwAMxC0s46i4pf1GGjLeuwUDz2iq96x11a4fj0VRFwr3hJQm5Y/YYbtmznKTxSETXhPSDZV9h2SZzoLAXyZAoMEc5oFRYNrZaCjoceLAI/9k1xLuBHYFZ3t2cuB3GLew=
  on:
    tags: true
    repo: enhancv/mongoose-subscriptions
